/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicChatwootWebhookRouteImport } from './routes/api/public/chatwoot-webhook'
import { Route as ApiPublicChatwootSendRouteImport } from './routes/api/public/chatwoot-send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatwootWebhookRoute =
  ApiPublicChatwootWebhookRouteImport.update({
    id: '/api/public/chatwoot-webhook',
    path: '/api/public/chatwoot-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatwootSendRoute = ApiPublicChatwootSendRouteImport.update({
  id: '/api/public/chatwoot-send',
  path: '/api/public/chatwoot-send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/chatwoot-send': typeof ApiPublicChatwootSendRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/chatwoot-send': typeof ApiPublicChatwootSendRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/chatwoot-send': typeof ApiPublicChatwootSendRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/chatwoot-send' | '/api/public/chatwoot-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/chatwoot-send' | '/api/public/chatwoot-webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/chatwoot-send'
    | '/api/public/chatwoot-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicChatwootSendRoute: typeof ApiPublicChatwootSendRoute
  ApiPublicChatwootWebhookRoute: typeof ApiPublicChatwootWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatwoot-webhook': {
      id: '/api/public/chatwoot-webhook'
      path: '/api/public/chatwoot-webhook'
      fullPath: '/api/public/chatwoot-webhook'
      preLoaderRoute: typeof ApiPublicChatwootWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatwoot-send': {
      id: '/api/public/chatwoot-send'
      path: '/api/public/chatwoot-send'
      fullPath: '/api/public/chatwoot-send'
      preLoaderRoute: typeof ApiPublicChatwootSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicChatwootSendRoute: ApiPublicChatwootSendRoute,
  ApiPublicChatwootWebhookRoute: ApiPublicChatwootWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
